# 详细配置文档: https://github.com/JixunMoe/jjBot/wiki/配置机器人
# Use space, not tabs.

# Max Retry for tx APIs
maxRetry: 3

# Your login info
qqnum:  '10000'
passwd: 'Your Password'

# Seconds to wait before process messages.
bootWait: 20

# 消息發送間隔; 0 表示不停留 (不推薦)
msgInterval: 200


# Spec. Path for your file/directorys.
logPath:  './jjBot.log'
webPath:  './www.d/'
cachePath: './cache.d/'
plugPath: './plug.d/'

# Which port to run web server?
port: 2333

# Command Prefix.
# E.g. jj, will accept commands like jj/hello
cmdPrefix: 'jj'

# User Agent to be used to communicate with tx's server.
userAgent: 'Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 5.1; SLCC1; .NET CLR 1.1.4322)'

# TODO: Ignore people's message
ban:
    - "110"
    - "10000"

# Message font config
font:
    colour: 'ff6600'
    size:   9
    name:   '宋体'

# Login info for web server
web:
    auth:
      'Admin': 'jjBot##ForYouxD'

# UC config
user:
    default:
        dMoneyLeft: 50
    signRange:
        min: 20
        max: 50
    currency: '喵币'

# MySQL Info
mysql:
    auth:
        host: localhost
        port: 3306
        user: root
        password: root
    database: jjBot
    engine:   InnoDB

# Plugin blacklist
# One per line.
blacklist:
    - fly