# 回复几率 (0 ~ 1)
replyRate: 0.5

# 回复等待的次数/每 .. 条消息回复一次
replyWait: 5

# 回应的模板, {{ xx }} 中的为变量名; 请参见下述地址的 [实例] -> [返回值] 区域
# http://hitokoto.us/api.html
# 
# 如果模板为多行, 请注意保留缩进 (即每行前面有 2 个空格)!!
tpl: |-
  {{ hitokoto }}
    -- {{ author }}//{{ source }}

# 一言的参数, 请参见下述地址的 [参数说明] 区域
# http://hitokoto.us/api.html
hitokoto:
    # 分类, 可以填写多个, 使用半角逗号区分
    cat: a
    # 一言的长度, 超过自动裁剪
    length: 0
    # 来源用户
    uid: 0
    # 不方便解释, 请参见上述地址自行领悟
    mix: 0
    ucat: 0